// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: overseer.proto

package overseer_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OverseerTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Callback string `protobuf:"bytes,1,opt,name=callback,proto3" json:"callback,omitempty"`
	Task     string `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
}

func (x *OverseerTask) Reset() {
	*x = OverseerTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_overseer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OverseerTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverseerTask) ProtoMessage() {}

func (x *OverseerTask) ProtoReflect() protoreflect.Message {
	mi := &file_overseer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverseerTask.ProtoReflect.Descriptor instead.
func (*OverseerTask) Descriptor() ([]byte, []int) {
	return file_overseer_proto_rawDescGZIP(), []int{0}
}

func (x *OverseerTask) GetCallback() string {
	if x != nil {
		return x.Callback
	}
	return ""
}

func (x *OverseerTask) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

type RegisterTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Callback string `protobuf:"bytes,1,opt,name=callback,proto3" json:"callback,omitempty"`
	Task     string `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
}

func (x *RegisterTaskRequest) Reset() {
	*x = RegisterTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_overseer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTaskRequest) ProtoMessage() {}

func (x *RegisterTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_overseer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTaskRequest.ProtoReflect.Descriptor instead.
func (*RegisterTaskRequest) Descriptor() ([]byte, []int) {
	return file_overseer_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterTaskRequest) GetCallback() string {
	if x != nil {
		return x.Callback
	}
	return ""
}

func (x *RegisterTaskRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

type RegisterTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisterTaskResponse) Reset() {
	*x = RegisterTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_overseer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTaskResponse) ProtoMessage() {}

func (x *RegisterTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_overseer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTaskResponse.ProtoReflect.Descriptor instead.
func (*RegisterTaskResponse) Descriptor() ([]byte, []int) {
	return file_overseer_proto_rawDescGZIP(), []int{2}
}

type OverseerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task string `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
}

func (x *OverseerRequest) Reset() {
	*x = OverseerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_overseer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OverseerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverseerRequest) ProtoMessage() {}

func (x *OverseerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_overseer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverseerRequest.ProtoReflect.Descriptor instead.
func (*OverseerRequest) Descriptor() ([]byte, []int) {
	return file_overseer_proto_rawDescGZIP(), []int{3}
}

func (x *OverseerRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

type OverseerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OverseerResponse) Reset() {
	*x = OverseerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_overseer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OverseerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverseerResponse) ProtoMessage() {}

func (x *OverseerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_overseer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverseerResponse.ProtoReflect.Descriptor instead.
func (*OverseerResponse) Descriptor() ([]byte, []int) {
	return file_overseer_proto_rawDescGZIP(), []int{4}
}

var File_overseer_proto protoreflect.FileDescriptor

var file_overseer_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x65, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x65, 0x65, 0x72, 0x22, 0x3e, 0x0a, 0x0c, 0x4f, 0x76,
	0x65, 0x72, 0x73, 0x65, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61,
	0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61,
	0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x22, 0x45, 0x0a, 0x13, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x73,
	0x6b, 0x22, 0x16, 0x0a, 0x14, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x25, 0x0a, 0x0f, 0x4f, 0x76, 0x65,
	0x72, 0x73, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x73, 0x6b,
	0x22, 0x12, 0x0a, 0x10, 0x4f, 0x76, 0x65, 0x72, 0x73, 0x65, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0x60, 0x0a, 0x0f, 0x4f, 0x76, 0x65, 0x72, 0x73, 0x65, 0x65, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4d, 0x0a, 0x0c, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x1d, 0x2e, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x65,
	0x65, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x65, 0x65,
	0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x53, 0x0a, 0x0e, 0x4f, 0x76, 0x65, 0x72, 0x73, 0x65,
	0x65, 0x72, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x41, 0x0a, 0x08, 0x4f, 0x76, 0x65, 0x72,
	0x73, 0x65, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x65, 0x65, 0x72, 0x2e,
	0x4f, 0x76, 0x65, 0x72, 0x73, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1a, 0x2e, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x65, 0x65, 0x72, 0x2e, 0x4f, 0x76, 0x65, 0x72, 0x73,
	0x65, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x28, 0x5a, 0x26, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x72, 0x6f, 0x74, 0x68, 0x65,
	0x72, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2f, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x65, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_overseer_proto_rawDescOnce sync.Once
	file_overseer_proto_rawDescData = file_overseer_proto_rawDesc
)

func file_overseer_proto_rawDescGZIP() []byte {
	file_overseer_proto_rawDescOnce.Do(func() {
		file_overseer_proto_rawDescData = protoimpl.X.CompressGZIP(file_overseer_proto_rawDescData)
	})
	return file_overseer_proto_rawDescData
}

var file_overseer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_overseer_proto_goTypes = []interface{}{
	(*OverseerTask)(nil),         // 0: overseer.OverseerTask
	(*RegisterTaskRequest)(nil),  // 1: overseer.RegisterTaskRequest
	(*RegisterTaskResponse)(nil), // 2: overseer.RegisterTaskResponse
	(*OverseerRequest)(nil),      // 3: overseer.OverseerRequest
	(*OverseerResponse)(nil),     // 4: overseer.OverseerResponse
}
var file_overseer_proto_depIdxs = []int32{
	1, // 0: overseer.OverseerService.RegisterTask:input_type -> overseer.RegisterTaskRequest
	3, // 1: overseer.OverseerClient.Overseer:input_type -> overseer.OverseerRequest
	2, // 2: overseer.OverseerService.RegisterTask:output_type -> overseer.RegisterTaskResponse
	4, // 3: overseer.OverseerClient.Overseer:output_type -> overseer.OverseerResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_overseer_proto_init() }
func file_overseer_proto_init() {
	if File_overseer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_overseer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OverseerTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_overseer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_overseer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_overseer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OverseerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_overseer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OverseerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_overseer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_overseer_proto_goTypes,
		DependencyIndexes: file_overseer_proto_depIdxs,
		MessageInfos:      file_overseer_proto_msgTypes,
	}.Build()
	File_overseer_proto = out.File
	file_overseer_proto_rawDesc = nil
	file_overseer_proto_goTypes = nil
	file_overseer_proto_depIdxs = nil
}
