// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: overseer.proto

package overseer_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidationResponse int32

const (
	ValidationResponse_VALIDATION_UNKNOWN         ValidationResponse = 0
	ValidationResponse_VALIDATION_FAILED_UNSTABLE ValidationResponse = 1
	ValidationResponse_VALIDATION_FAILED          ValidationResponse = 2
	ValidationResponse_VALIDATION_PASSED          ValidationResponse = 3
)

// Enum value maps for ValidationResponse.
var (
	ValidationResponse_name = map[int32]string{
		0: "VALIDATION_UNKNOWN",
		1: "VALIDATION_FAILED_UNSTABLE",
		2: "VALIDATION_FAILED",
		3: "VALIDATION_PASSED",
	}
	ValidationResponse_value = map[string]int32{
		"VALIDATION_UNKNOWN":         0,
		"VALIDATION_FAILED_UNSTABLE": 1,
		"VALIDATION_FAILED":          2,
		"VALIDATION_PASSED":          3,
	}
)

func (x ValidationResponse) Enum() *ValidationResponse {
	p := new(ValidationResponse)
	*p = x
	return p
}

func (x ValidationResponse) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidationResponse) Descriptor() protoreflect.EnumDescriptor {
	return file_overseer_proto_enumTypes[0].Descriptor()
}

func (ValidationResponse) Type() protoreflect.EnumType {
	return &file_overseer_proto_enumTypes[0]
}

func (x ValidationResponse) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidationResponse.Descriptor instead.
func (ValidationResponse) EnumDescriptor() ([]byte, []int) {
	return file_overseer_proto_rawDescGZIP(), []int{0}
}

type RepoChange int32

const (
	RepoChange_REPO_CHANGE_UNKNOWN                RepoChange = 0
	RepoChange_REPO_CHANGE_DO_NOTHING             RepoChange = 1
	RepoChange_REPO_CHANGE_BUMP_MILESTONE_VERSION RepoChange = 2
	RepoChange_REPO_CHANGE_BUMP_STABLE_VERSION    RepoChange = 3
)

// Enum value maps for RepoChange.
var (
	RepoChange_name = map[int32]string{
		0: "REPO_CHANGE_UNKNOWN",
		1: "REPO_CHANGE_DO_NOTHING",
		2: "REPO_CHANGE_BUMP_MILESTONE_VERSION",
		3: "REPO_CHANGE_BUMP_STABLE_VERSION",
	}
	RepoChange_value = map[string]int32{
		"REPO_CHANGE_UNKNOWN":                0,
		"REPO_CHANGE_DO_NOTHING":             1,
		"REPO_CHANGE_BUMP_MILESTONE_VERSION": 2,
		"REPO_CHANGE_BUMP_STABLE_VERSION":    3,
	}
)

func (x RepoChange) Enum() *RepoChange {
	p := new(RepoChange)
	*p = x
	return p
}

func (x RepoChange) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RepoChange) Descriptor() protoreflect.EnumDescriptor {
	return file_overseer_proto_enumTypes[1].Descriptor()
}

func (RepoChange) Type() protoreflect.EnumType {
	return &file_overseer_proto_enumTypes[1]
}

func (x RepoChange) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RepoChange.Descriptor instead.
func (RepoChange) EnumDescriptor() ([]byte, []int) {
	return file_overseer_proto_rawDescGZIP(), []int{1}
}

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tasks []*OverseerTask `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_overseer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_overseer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_overseer_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetTasks() []*OverseerTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type ValidationRun struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimestampMs    int64              `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	RunningVersion string             `protobuf:"bytes,4,opt,name=running_version,json=runningVersion,proto3" json:"running_version,omitempty"`
	Response       ValidationResponse `protobuf:"varint,2,opt,name=response,proto3,enum=overseer.ValidationResponse" json:"response,omitempty"`
	CanonicalCode  string             `protobuf:"bytes,3,opt,name=canonical_code,json=canonicalCode,proto3" json:"canonical_code,omitempty"`
}

func (x *ValidationRun) Reset() {
	*x = ValidationRun{}
	if protoimpl.UnsafeEnabled {
		mi := &file_overseer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidationRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationRun) ProtoMessage() {}

func (x *ValidationRun) ProtoReflect() protoreflect.Message {
	mi := &file_overseer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationRun.ProtoReflect.Descriptor instead.
func (*ValidationRun) Descriptor() ([]byte, []int) {
	return file_overseer_proto_rawDescGZIP(), []int{1}
}

func (x *ValidationRun) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *ValidationRun) GetRunningVersion() string {
	if x != nil {
		return x.RunningVersion
	}
	return ""
}

func (x *ValidationRun) GetResponse() ValidationResponse {
	if x != nil {
		return x.Response
	}
	return ValidationResponse_VALIDATION_UNKNOWN
}

func (x *ValidationRun) GetCanonicalCode() string {
	if x != nil {
		return x.CanonicalCode
	}
	return ""
}

type RepoAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimestampMs      int64      `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	RecorddedVersion string     `protobuf:"bytes,2,opt,name=recordded_version,json=recorddedVersion,proto3" json:"recordded_version,omitempty"`
	Action           RepoChange `protobuf:"varint,3,opt,name=action,proto3,enum=overseer.RepoChange" json:"action,omitempty"`
	NewVersion       string     `protobuf:"bytes,4,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
}

func (x *RepoAction) Reset() {
	*x = RepoAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_overseer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepoAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoAction) ProtoMessage() {}

func (x *RepoAction) ProtoReflect() protoreflect.Message {
	mi := &file_overseer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoAction.ProtoReflect.Descriptor instead.
func (*RepoAction) Descriptor() ([]byte, []int) {
	return file_overseer_proto_rawDescGZIP(), []int{2}
}

func (x *RepoAction) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *RepoAction) GetRecorddedVersion() string {
	if x != nil {
		return x.RecorddedVersion
	}
	return ""
}

func (x *RepoAction) GetAction() RepoChange {
	if x != nil {
		return x.Action
	}
	return RepoChange_REPO_CHANGE_UNKNOWN
}

func (x *RepoAction) GetNewVersion() string {
	if x != nil {
		return x.NewVersion
	}
	return ""
}

type OverseerTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid           string           `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Callback       string           `protobuf:"bytes,2,opt,name=callback,proto3" json:"callback,omitempty"`
	Task           string           `protobuf:"bytes,3,opt,name=task,proto3" json:"task,omitempty"`
	Repo           string           `protobuf:"bytes,7,opt,name=repo,proto3" json:"repo,omitempty"`
	ValidationRuns []*ValidationRun `protobuf:"bytes,4,rep,name=validation_runs,json=validationRuns,proto3" json:"validation_runs,omitempty"`
	DelayInS       int64            `protobuf:"varint,5,opt,name=delay_in_s,json=delayInS,proto3" json:"delay_in_s,omitempty"`
	RunOnChange    bool             `protobuf:"varint,6,opt,name=run_on_change,json=runOnChange,proto3" json:"run_on_change,omitempty"`
	RepoChange     RepoChange       `protobuf:"varint,8,opt,name=repo_change,json=repoChange,proto3,enum=overseer.RepoChange" json:"repo_change,omitempty"`
}

func (x *OverseerTask) Reset() {
	*x = OverseerTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_overseer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OverseerTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverseerTask) ProtoMessage() {}

func (x *OverseerTask) ProtoReflect() protoreflect.Message {
	mi := &file_overseer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverseerTask.ProtoReflect.Descriptor instead.
func (*OverseerTask) Descriptor() ([]byte, []int) {
	return file_overseer_proto_rawDescGZIP(), []int{3}
}

func (x *OverseerTask) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *OverseerTask) GetCallback() string {
	if x != nil {
		return x.Callback
	}
	return ""
}

func (x *OverseerTask) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *OverseerTask) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *OverseerTask) GetValidationRuns() []*ValidationRun {
	if x != nil {
		return x.ValidationRuns
	}
	return nil
}

func (x *OverseerTask) GetDelayInS() int64 {
	if x != nil {
		return x.DelayInS
	}
	return 0
}

func (x *OverseerTask) GetRunOnChange() bool {
	if x != nil {
		return x.RunOnChange
	}
	return false
}

func (x *OverseerTask) GetRepoChange() RepoChange {
	if x != nil {
		return x.RepoChange
	}
	return RepoChange_REPO_CHANGE_UNKNOWN
}

type RegisterTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Callback string `protobuf:"bytes,1,opt,name=callback,proto3" json:"callback,omitempty"`
	Task     string `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
}

func (x *RegisterTaskRequest) Reset() {
	*x = RegisterTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_overseer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTaskRequest) ProtoMessage() {}

func (x *RegisterTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_overseer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTaskRequest.ProtoReflect.Descriptor instead.
func (*RegisterTaskRequest) Descriptor() ([]byte, []int) {
	return file_overseer_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterTaskRequest) GetCallback() string {
	if x != nil {
		return x.Callback
	}
	return ""
}

func (x *RegisterTaskRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

type RegisterTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisterTaskResponse) Reset() {
	*x = RegisterTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_overseer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTaskResponse) ProtoMessage() {}

func (x *RegisterTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_overseer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTaskResponse.ProtoReflect.Descriptor instead.
func (*RegisterTaskResponse) Descriptor() ([]byte, []int) {
	return file_overseer_proto_rawDescGZIP(), []int{5}
}

type OverseerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task string `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
}

func (x *OverseerRequest) Reset() {
	*x = OverseerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_overseer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OverseerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverseerRequest) ProtoMessage() {}

func (x *OverseerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_overseer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverseerRequest.ProtoReflect.Descriptor instead.
func (*OverseerRequest) Descriptor() ([]byte, []int) {
	return file_overseer_proto_rawDescGZIP(), []int{6}
}

func (x *OverseerRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

type OverseerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response ValidationResponse `protobuf:"varint,1,opt,name=response,proto3,enum=overseer.ValidationResponse" json:"response,omitempty"`
}

func (x *OverseerResponse) Reset() {
	*x = OverseerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_overseer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OverseerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverseerResponse) ProtoMessage() {}

func (x *OverseerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_overseer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverseerResponse.ProtoReflect.Descriptor instead.
func (*OverseerResponse) Descriptor() ([]byte, []int) {
	return file_overseer_proto_rawDescGZIP(), []int{7}
}

func (x *OverseerResponse) GetResponse() ValidationResponse {
	if x != nil {
		return x.Response
	}
	return ValidationResponse_VALIDATION_UNKNOWN
}

var File_overseer_proto protoreflect.FileDescriptor

var file_overseer_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x65, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x65, 0x65, 0x72, 0x22, 0x36, 0x0a, 0x06, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x2c, 0x0a, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x65, 0x65, 0x72, 0x2e, 0x4f,
	0x76, 0x65, 0x72, 0x73, 0x65, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x05, 0x74, 0x61, 0x73,
	0x6b, 0x73, 0x22, 0xbc, 0x01, 0x0a, 0x0d, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x75, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x5f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x4d, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x75, 0x6e, 0x6e, 0x69,
	0x6e, 0x67, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x38, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x65, 0x65, 0x72, 0x2e, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x61,
	0x6e, 0x6f, 0x6e, 0x69, 0x63, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x63, 0x61, 0x6e, 0x6f, 0x6e, 0x69, 0x63, 0x61, 0x6c, 0x43, 0x6f, 0x64,
	0x65, 0x22, 0xab, 0x01, 0x0a, 0x0a, 0x52, 0x65, 0x70, 0x6f, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x21, 0x0a, 0x0c, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x6d, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x4d, 0x73, 0x12, 0x2b, 0x0a, 0x11, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x64, 0x65, 0x64,
	0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x64, 0x65, 0x64, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x2c, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x14, 0x2e, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x65, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x70, 0x6f,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f,
	0x0a, 0x0b, 0x6e, 0x65, 0x77, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x65, 0x77, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22,
	0xa1, 0x02, 0x0a, 0x0c, 0x4f, 0x76, 0x65, 0x72, 0x73, 0x65, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x61, 0x73, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x12, 0x40, 0x0a, 0x0f, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x75, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x65, 0x65, 0x72, 0x2e, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x75, 0x6e, 0x52, 0x0e, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x75, 0x6e, 0x73, 0x12, 0x1c, 0x0a, 0x0a, 0x64, 0x65,
	0x6c, 0x61, 0x79, 0x5f, 0x69, 0x6e, 0x5f, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x64, 0x65, 0x6c, 0x61, 0x79, 0x49, 0x6e, 0x53, 0x12, 0x22, 0x0a, 0x0d, 0x72, 0x75, 0x6e, 0x5f,
	0x6f, 0x6e, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0b, 0x72, 0x75, 0x6e, 0x4f, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x35, 0x0a, 0x0b,
	0x72, 0x65, 0x70, 0x6f, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x14, 0x2e, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x65, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x70,
	0x6f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x0a, 0x72, 0x65, 0x70, 0x6f, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x22, 0x45, 0x0a, 0x13, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54,
	0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61,
	0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61,
	0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x22, 0x16, 0x0a, 0x14, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x25, 0x0a, 0x0f, 0x4f, 0x76, 0x65, 0x72, 0x73, 0x65, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x22, 0x4c, 0x0a, 0x10, 0x4f, 0x76, 0x65,
	0x72, 0x73, 0x65, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1c, 0x2e, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x65, 0x65, 0x72, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x7a, 0x0a, 0x12, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x12, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x1e, 0x0a, 0x1a, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x41, 0x54,
	0x49, 0x4f, 0x4e, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x5f, 0x55, 0x4e, 0x53, 0x54, 0x41,
	0x42, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x41, 0x54,
	0x49, 0x4f, 0x4e, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11,
	0x56, 0x41, 0x4c, 0x49, 0x44, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x50, 0x41, 0x53, 0x53, 0x45,
	0x44, 0x10, 0x03, 0x2a, 0x8e, 0x01, 0x0a, 0x0a, 0x52, 0x65, 0x70, 0x6f, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x45, 0x50, 0x4f, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x47,
	0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x52,
	0x45, 0x50, 0x4f, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x44, 0x4f, 0x5f, 0x4e, 0x4f,
	0x54, 0x48, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x26, 0x0a, 0x22, 0x52, 0x45, 0x50, 0x4f, 0x5f,
	0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x42, 0x55, 0x4d, 0x50, 0x5f, 0x4d, 0x49, 0x4c, 0x45,
	0x53, 0x54, 0x4f, 0x4e, 0x45, 0x5f, 0x56, 0x45, 0x52, 0x53, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x12,
	0x23, 0x0a, 0x1f, 0x52, 0x45, 0x50, 0x4f, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x42,
	0x55, 0x4d, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x42, 0x4c, 0x45, 0x5f, 0x56, 0x45, 0x52, 0x53, 0x49,
	0x4f, 0x4e, 0x10, 0x03, 0x32, 0x60, 0x0a, 0x0f, 0x4f, 0x76, 0x65, 0x72, 0x73, 0x65, 0x65, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4d, 0x0a, 0x0c, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x1d, 0x2e, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x65,
	0x65, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x65, 0x65,
	0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x53, 0x0a, 0x0e, 0x4f, 0x76, 0x65, 0x72, 0x73, 0x65,
	0x65, 0x72, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x41, 0x0a, 0x08, 0x4f, 0x76, 0x65, 0x72,
	0x73, 0x65, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x65, 0x65, 0x72, 0x2e,
	0x4f, 0x76, 0x65, 0x72, 0x73, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1a, 0x2e, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x65, 0x65, 0x72, 0x2e, 0x4f, 0x76, 0x65, 0x72, 0x73,
	0x65, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x28, 0x5a, 0x26, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x72, 0x6f, 0x74, 0x68, 0x65,
	0x72, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2f, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x65, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_overseer_proto_rawDescOnce sync.Once
	file_overseer_proto_rawDescData = file_overseer_proto_rawDesc
)

func file_overseer_proto_rawDescGZIP() []byte {
	file_overseer_proto_rawDescOnce.Do(func() {
		file_overseer_proto_rawDescData = protoimpl.X.CompressGZIP(file_overseer_proto_rawDescData)
	})
	return file_overseer_proto_rawDescData
}

var file_overseer_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_overseer_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_overseer_proto_goTypes = []interface{}{
	(ValidationResponse)(0),      // 0: overseer.ValidationResponse
	(RepoChange)(0),              // 1: overseer.RepoChange
	(*Config)(nil),               // 2: overseer.Config
	(*ValidationRun)(nil),        // 3: overseer.ValidationRun
	(*RepoAction)(nil),           // 4: overseer.RepoAction
	(*OverseerTask)(nil),         // 5: overseer.OverseerTask
	(*RegisterTaskRequest)(nil),  // 6: overseer.RegisterTaskRequest
	(*RegisterTaskResponse)(nil), // 7: overseer.RegisterTaskResponse
	(*OverseerRequest)(nil),      // 8: overseer.OverseerRequest
	(*OverseerResponse)(nil),     // 9: overseer.OverseerResponse
}
var file_overseer_proto_depIdxs = []int32{
	5, // 0: overseer.Config.tasks:type_name -> overseer.OverseerTask
	0, // 1: overseer.ValidationRun.response:type_name -> overseer.ValidationResponse
	1, // 2: overseer.RepoAction.action:type_name -> overseer.RepoChange
	3, // 3: overseer.OverseerTask.validation_runs:type_name -> overseer.ValidationRun
	1, // 4: overseer.OverseerTask.repo_change:type_name -> overseer.RepoChange
	0, // 5: overseer.OverseerResponse.response:type_name -> overseer.ValidationResponse
	6, // 6: overseer.OverseerService.RegisterTask:input_type -> overseer.RegisterTaskRequest
	8, // 7: overseer.OverseerClient.Overseer:input_type -> overseer.OverseerRequest
	7, // 8: overseer.OverseerService.RegisterTask:output_type -> overseer.RegisterTaskResponse
	9, // 9: overseer.OverseerClient.Overseer:output_type -> overseer.OverseerResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_overseer_proto_init() }
func file_overseer_proto_init() {
	if File_overseer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_overseer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_overseer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidationRun); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_overseer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepoAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_overseer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OverseerTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_overseer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_overseer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_overseer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OverseerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_overseer_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OverseerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_overseer_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_overseer_proto_goTypes,
		DependencyIndexes: file_overseer_proto_depIdxs,
		EnumInfos:         file_overseer_proto_enumTypes,
		MessageInfos:      file_overseer_proto_msgTypes,
	}.Build()
	File_overseer_proto = out.File
	file_overseer_proto_rawDesc = nil
	file_overseer_proto_goTypes = nil
	file_overseer_proto_depIdxs = nil
}
